import React from 'react'
import { useReactFlow } from '@xyflow/react'
import { useDiagramStore } from '../../store/diagramStore'
import type { Position } from '../../types/diagram'
import type { OrthoPoint } from '../../utils/orthogonalRouting'

interface WaypointHandlesProps {
  edgeId: string
  sourceX: number
  sourceY: number
  targetX: number
  targetY: number
  routePoints: Position[]
  orthoPoints: OrthoPoint[]
}

/*
 * WaypointHandles renders interactive segment lines and display dots for waypoint vertices.
 *
 * Responsibility:
 * - Reads orthoPoints (orthogonal path generated by renderer) to overlay handles.
 * - Restricts dragging of internal segments to their orthogonal axis (horizontal -> vertical, vertical -> horizontal).
 * - Maps segment movements back to the underlying routePoints document model.
 * - Supports splitting any segment via double-click to add waypoints.
 * - Supports double-clicking waypoint vertex circles to delete them.
 */
export function WaypointHandles({
  edgeId,
  routePoints,
  orthoPoints,
}: WaypointHandlesProps) {
  const updateEdgeRoutePoints = useDiagramStore((state) => state.updateEdgeRoutePoints)
  const deleteWaypoint = useDiagramStore((state) => state.deleteWaypoint)
  const addWaypoint = useDiagramStore((state) => state.addWaypoint)
  const { getZoom, screenToFlowPosition } = useReactFlow()

  // 1. Identify all segments from the rendered orthogonal path
  const allSegments = []
  for (let j = 0; j < orthoPoints.length - 1; j++) {
    const p1 = orthoPoints[j]
    const p2 = orthoPoints[j + 1]
    const isHorizontal = Math.abs(p1.x - p2.x) >= Math.abs(p1.y - p2.y)
    
    // First segment (j = 0) and last segment (j = orthoPoints.length - 2) are locked
    const isLocked = j === 0 || j === orthoPoints.length - 2

    allSegments.push({
      index: j,
      p1,
      p2,
      isHorizontal,
      isLocked,
      w1: p1.waypointIndex,
      w2: p2.waypointIndex,
    })
  }

  // 2. Handle dragging an editable segment
  const handleSegmentMouseDown = (
    e: React.MouseEvent,
    w1: number,
    w2: number,
    isHorizontal: boolean
  ) => {
    e.stopPropagation()
    e.preventDefault()

    const startX = e.clientX
    const startY = e.clientY
    const zoom = getZoom()

    const initialPoints = [...routePoints]
    const initialW1 = w1 >= 0 && w1 < routePoints.length ? { ...initialPoints[w1] } : null
    const initialW2 = w2 >= 0 && w2 < routePoints.length ? { ...initialPoints[w2] } : null

    const handleMouseMove = (moveEvent: MouseEvent) => {
      const dx = isHorizontal ? 0 : (moveEvent.clientX - startX) / zoom
      const dy = isHorizontal ? (moveEvent.clientY - startY) / zoom : 0

      const updatedPoints = routePoints.map((pt, idx) => {
        const newPt = { ...pt }
        if (idx === w1 && initialW1) {
          newPt.x = Math.round(initialW1.x + dx)
          newPt.y = Math.round(initialW1.y + dy)
        }
        if (idx === w2 && initialW2) {
          newPt.x = Math.round(initialW2.x + dx)
          newPt.y = Math.round(initialW2.y + dy)
        }
        return newPt
      })

      // Skip saving to history during active drag
      updateEdgeRoutePoints(edgeId, updatedPoints, true)
    }

    const handleMouseUp = (upEvent: MouseEvent) => {
      window.removeEventListener('mousemove', handleMouseMove)
      window.removeEventListener('mouseup', handleMouseUp)

      const dx = isHorizontal ? 0 : (upEvent.clientX - startX) / zoom
      const dy = isHorizontal ? (upEvent.clientY - startY) / zoom : 0

      const updatedPoints = routePoints.map((pt, idx) => {
        const newPt = { ...pt }
        if (idx === w1 && initialW1) {
          newPt.x = Math.round(initialW1.x + dx)
          newPt.y = Math.round(initialW1.y + dy)
        }
        if (idx === w2 && initialW2) {
          newPt.x = Math.round(initialW2.x + dx)
          newPt.y = Math.round(initialW2.y + dy)
        }
        return newPt
      })
      
      // Commit final position to history
      updateEdgeRoutePoints(edgeId, updatedPoints, false)
    }

    window.addEventListener('mousemove', handleMouseMove)
    window.addEventListener('mouseup', handleMouseUp)
  }

  const handleDoubleClick = (e: React.MouseEvent, index: number) => {
    e.stopPropagation()
    e.preventDefault()
    deleteWaypoint(edgeId, index)
  }

  return (
    <g className="waypoint-handles">
      {/* Render interaction and highlighted overlays for segments */}
      {allSegments.map((seg) => (
        <g key={`${edgeId}-segment-${seg.index}`} className="orthogonal-segment-overlay">
          {/* Thick invisible interaction segment to capture drag/double-clicks easily */}
          <line
            x1={seg.p1.x}
            y1={seg.p1.y}
            x2={seg.p2.x}
            y2={seg.p2.y}
            stroke="transparent"
            strokeWidth={12}
            style={{
              cursor: seg.isLocked ? 'default' : 'grab',
              pointerEvents: 'all',
            }}
            onMouseDown={(e) => {
              if (!seg.isLocked) {
                handleSegmentMouseDown(e, seg.w1, seg.w2, seg.isHorizontal)
              }
            }}
            onDoubleClick={(e) => {
              e.stopPropagation()
              e.preventDefault()
              const pos = screenToFlowPosition({ x: e.clientX, y: e.clientY })
              // Insert waypoint at the target waypointIndex corresponding to the segment end
              addWaypoint(edgeId, pos, seg.w2)
            }}
          />
          
          {/* Render visual blue dashes only on editable/movable internal segments */}
          {!seg.isLocked && (
            <line
              x1={seg.p1.x}
              y1={seg.p1.y}
              x2={seg.p2.x}
              y2={seg.p2.y}
              stroke="#3b82f6"
              strokeWidth={2.5}
              strokeDasharray="4 4"
              style={{ pointerEvents: 'none' }}
            />
          )}
        </g>
      ))}

      {/* Render small vertex display dots at actual waypoint positions */}
      {routePoints.map((pt, index) => (
        <circle
          key={`${edgeId}-waypoint-${index}`}
          cx={pt.x}
          cy={pt.y}
          r={5}
          fill="#3b82f6"
          stroke="#ffffff"
          strokeWidth={1.5}
          style={{ cursor: 'pointer', pointerEvents: 'all' }}
          onDoubleClick={(e) => handleDoubleClick(e, index)}
        >
          <title>Double-click to delete waypoint</title>
        </circle>
      ))}
    </g>
  )
}
